### PR TITLE
Move js2coffee to npm module, update to js2coffee 0.2.2, make options work. #1

### PR DESCRIPTION
**Pull request by alexandrosm**
Please find the pull request as discussed in issue #1. Tests fail as the test files aren't there, but the new plugin works for my code so hopefully all is ok.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
awesome, thanks!

**Comment by alexandrosm** [comment]
Do you mind giving this a version bump so I can set it in my package.json? Cheers!

**Comment by alexandrosm** [comment]
Thanks for all your work on this btw, this is what I'm using it for: https://github.com/yeoman/grunt-bower-requirejs/wiki/Using-with-CoffeeScript

**Comment by jonschlinkert** [comment]
No prob! I bumped and published about 5 min after I merged, so you should be good to go. Glad it's useful!

**Pull request merged**
